DROP TABLE ZONAS_PREFERIDAS;
DROP TABLE PRODUCTOS_PREFERIDOS;
DROP TABLE HISTORIAL;
DROP TABLE CAPACIDADES_TECNICAS;
DROP TABLE ITEMS;
DROP TABLE INGREDIENTES_PRODUCTIND;
DROP TABLE MENU_PRODUCTO_INDIVIDUAL;
DROP TABLE RESERVAS;
DROP TABLE MENUS;
DROP TABLE INGREDIENTES;
DROP TABLE CARRITOS;
DROP TABLE PRODUCTOS_INDIVIDUALES;
DROP TABLE PRODUCTOS;
DROP TABLE RESTAURANTES;
DROP TABLE USUARIOS_REGISTRADOS;
DROP TABLE ZONAS;
DROP TABLE USUARIOS;


CREATE TABLE USUARIOS (
id NUMBER(10)NOT NULL PRIMARY KEY,
nombres VARCHAR2(30) NOT NULL,
apellidos VARCHAR2(30) NOT NULL,
tipoId VARCHAR2(5) NOT NULL,
numId NUMBER(10) NOT NULL);

CREATE TABLE ZONAS(
nombre VARCHAR(20)NOT NULL PRIMARY KEY,
cerrado NUMBER(1) NOT NULL CHECK(cerrado=1 OR cerrado=0),
tipo VARCHAR(20),
aptoDiscap NUMBER(1)NOT NULL CHECK(aptoDiscap=1 OR aptoDiscap=0),
capacidad NUMBER(10) NOT NULL
);
CREATE TABLE USUARIOS_REGISTRADOS (
  ID NUMBER(10) NOT NULL PRIMARY KEY ,
  LOGIN VARCHAR2(20) NOT NULL,
  PASSWORD VARCHAR2(20) NOT NULL,
  CONSTRAINT FK_USUARIOS FOREIGN KEY (ID) REFERENCES USUARIOS(ID)
);

CREATE TABLE RESTAURANTES (
  ID NUMBER(10) PRIMARY KEY ,
  NOMBRE VARCHAR2(50) NOT NULL ,
  TIPO VARCHAR2(20),
  PAGINA_WEB VARCHAR2(100),
  ZONA VARCHAR2(20) NOT NULL,
  CONSTRAINT FK_ZONA FOREIGN KEY (ZONA) REFERENCES ZONAS(NOMBRE)
);

CREATE TABLE PRODUCTOS(
id NUMBER(10) NOT NULL PRIMARY KEY,
nombre VARCHAR2(20) NOT NULL,
descrEsp VARCHAR2(200),
descrIng VARCHAR2(200),
tPrep NUMBER(15,5) NOT NULL,
costo NUMBER(15,5) NOT NULL,
precio NUMBER(15,5) NOT NULL,
restaurantes_id NUMBER(10) NOT NULL,
CONSTRAINT FK_RESTAURANTES_PRODUCTOS
        FOREIGN KEY (restaurantes_id)
        REFERENCES RESTAURANTES(id)
);

CREATE TABLE PRODUCTOS_INDIVIDUALES(
id NUMBER(10) NOT NULL PRIMARY KEY,
categoria VARCHAR2(20) NOT NULL,
grupo NUMBER(10) NOT NULL,
CONSTRAINT FK_PRODUCTOS
        FOREIGN KEY (id)
        REFERENCES PRODUCTOS(id)
);

CREATE TABLE CARRITOS(
id NUMBER(10) NOT NULL PRIMARY KEY,
nombre VARCHAR2(20) NOT NULL,
costo NUMBER(15,5) NOT NULL,
usuario_id NUMBER(10) NOT NULL,
CONSTRAINT FK_CARRITOS
        FOREIGN KEY (usuario_id)
        REFERENCES USUARIOS(id)
);

CREATE TABLE INGREDIENTES (
  ID NUMBER(10) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR2(30) NOT NULL,
  DESCRESP VARCHAR2(200) ,
  DESCRING VARCHAR(200) ,
  GRUPO INTEGER NOT NULL,
  RESTAURANTE NUMBER(10),
  CONSTRAINT FK_RESTAURANTE FOREIGN KEY (RESTAURANTE) REFERENCES RESTAURANTES(ID)
);

CREATE TABLE MENUS (
  ID NUMBER(10) NOT NULL PRIMARY KEY,
  CONSTRAINT FK_PRODUCTOS_MENUS FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
);

CREATE TABLE RESERVAS(
id NUMBER(10) PRIMARY KEY,
fechaInicio DATE NOT NULL,
fechaFin DATE NOT NULL,
numComensales NUMBER(10) NOT NULL,
usuariosRegistrados_id NUMBER(10) NOT NULL,
zonas_nombre VARCHAR(20) NOT NULL,
menus_productos_id NUMBER(10),
CONSTRAINT FK_USUARIOSREG FOREIGN KEY(usuariosRegistrados_id)
REFERENCES USUARIOS_REGISTRADOS(ID),
CONSTRAINT FK_ZONASNOM FOREIGN KEY(zonas_nombre)
REFERENCES ZONAS(NOMBRE),
CONSTRAINT FK_MENUSPRODUCTO FOREIGN KEY(menus_productos_id)
REFERENCES MENUS(ID)
);

CREATE TABLE MENU_PRODUCTO_INDIVIDUAL (
  ID_MENU NUMBER(10) ,
  ID_PROD_INDIVIDUAL NUMBER(10) ,
  CONSTRAINT FK_MENU_PRODINF FOREIGN KEY (ID_MENU) REFERENCES MENUS(ID),
  CONSTRAINT FK_PRODINF_MENU FOREIGN KEY (ID_PROD_INDIVIDUAL) REFERENCES PRODUCTOS_INDIVIDUALES(ID),
  CONSTRAINT MENU_PRODUCTO_INDIVIDUAL_PK PRIMARY KEY (ID_MENU,ID_PROD_INDIVIDUAL)
);
CREATE TABLE INGREDIENTES_PRODUCTIND (
  ID_INGREDIENTE NUMBER(10),
  ID_PRODINDIVIDUAL NUMBER(10),
  CONSTRAINT FK_INGRED_PRODIND FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(ID),
  CONSTRAINT FK_PRODIND_INGRED FOREIGN KEY (ID_PRODINDIVIDUAL) REFERENCES PRODUCTOS_INDIVIDUALES(ID),
  CONSTRAINT INGRED_PRODUCTIND_PK PRIMARY KEY (ID_INGREDIENTE,ID_PRODINDIVIDUAL)
);
CREATE TABLE ITEMS (
  ID NUMBER(10) PRIMARY KEY ,
  PERSONALIZACION VARCHAR2(100),
  ID_PRODUCTO NUMBER(10) NOT NULL ,
  ID_CARRITO NUMBER(10),
  CONSTRAINT ITEM_PRODUCTO_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID),
  CONSTRAINT ITEM_CARRITO_FK FOREIGN KEY (ID_CARRITO) REFERENCES CARRITOS(ID)
);
CREATE TABLE CAPACIDADES_TECNICAS (
  NOMBRE VARCHAR2(30) PRIMARY KEY ,
  DESCRIPCION VARCHAR2(200),
  ZONA VARCHAR2(20) NOT NULL ,
  CONSTRAINT CAPACIDADES_TECNICAS_ZONA_FK FOREIGN KEY (ZONA) REFERENCES ZONAS(NOMBRE)
);
CREATE TABLE HISTORIAL (
  ID_PRODUCTO NUMBER(10) NOT NULL,
  ID_USUARIO_REGISTRADO NUMBER(10) NOT NULL,
  CONSTRAINT HISTORIAL_PROD_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID),
  CONSTRAINT HISTORIAL_USR_REG_FK FOREIGN KEY (ID_USUARIO_REGISTRADO) REFERENCES USUARIOS_REGISTRADOS(ID),
  CONSTRAINT HISTORIAL_PK PRIMARY KEY (ID_PRODUCTO,ID_USUARIO_REGISTRADO)
);
CREATE TABLE PRODUCTOS_PREFERIDOS (
  ID_PRODUCTO NUMBER(10) NOT NULL,
  ID_USUARIO_REGISTRADO NUMBER(10) NOT NULL,
  CONSTRAINT PROD_PREF_PROD_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID),
  CONSTRAINT PROD_PREF_USR_REG FOREIGN KEY (ID_USUARIO_REGISTRADO) REFERENCES USUARIOS_REGISTRADOS(ID),
  CONSTRAINT PRODUCTOS_PREFERIDOS_PK PRIMARY KEY (ID_PRODUCTO,ID_USUARIO_REGISTRADO)
);

CREATE TABLE ZONAS_PREFERIDAS(
usuariosRegistrados_id NUMBER(10) NOT NULL,
zonas_nombre VARCHAR(20) NOT NULL,
CONSTRAINT FK_USUARIOSREG1 FOREIGN KEY(usuariosRegistrados_id)
REFERENCES USUARIOS_REGISTRADOS(ID),
CONSTRAINT FK_ZONASNOM1 FOREIGN KEY(zonas_nombre)
REFERENCES ZONAS(NOMBRE),
CONSTRAINT PK_ZONAS_PREFERIDAS PRIMARY KEY(usuariosRegistrados_id, zonas_nombre)
);
